name: 'Copy Service CI'
on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env: # Or as an environment variable
        NPM_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
